{% set version = "5.0.3" %}

package:
  name: traitlets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traitlets/traitlets-{{ version }}.tar.gz
  sha256: a2e91709a0330b6c5d497ed470b2feb1ed8da5c9dd807c6daab41f727b9391c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ipython_genutils

test:
  imports:
    - traitlets
    - traitlets.config

about:
  home: http://traitlets.readthedocs.org/
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Configuration system for Python applications

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - SylvainCorlay
    - ocefpaf
    - Carreau
    - takluyver
    - rmorshea
    - blink1073
    - zsailer
