{% set version = "5.11.1" %}

package:
  name: traitlets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traitlets/traitlets-{{ version }}.tar.gz
  sha256: 813584bb569ac4a098c64ca494e8a3bbfef42e37c36a6132bca554aabd111480

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling >=1.5
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  source_files:
    - tests
  imports:
    - traitlets
    - traitlets.config
  commands:
    - pip check
    - coverage run --source=traitlets --parallel --branch -m pytest -vv
    - coverage run --source=traitlets --parallel --branch -m pytest -vv --pyargs traitlets
    - coverage combine
    - coverage report --show-missing --skip-covered --fail-under=88
    - mypy -p traitlets
  requires:
    - argcomplete >=3.0.3
    - coverage
    - mypy >=1.5.1
    - pip
    - pytest >=7.0,<7.5
    - pytest-mock
    - pytest-mypy-testing

about:
  home: https://traitlets.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Configuration system for Python applications
  dev_url: https://github.com/ipython/traitlets
  doc_url: https://traitlets.readthedocs.org

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - SylvainCorlay
    - ocefpaf
    - Carreau
    - takluyver
    - rmorshea
    - blink1073
    - zsailer
    - bollwyvl
    - davidbrochart
